# Generated by Django 2.0.2 on 2019-04-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
